version: '3.8'

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik-louis"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # !!! IMPORTANTE: Troque pelo seu email para o Let's Encrypt !!!
      - "--certificatesresolvers.myresolver.acme.email=pardinithales@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # Redireciona todo tráfego HTTP para HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      # Portas para tráfego web (HTTP e HTTPS)
      - "80:80"
      - "443:443"
      # Porta para o Dashboard do Traefik (opcional, para debug)
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt_data:/letsencrypt"
    networks:
      - louis_net
    restart: always

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: louis-backend-prod
    restart: always
    volumes:
      - ./images:/app/images
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - louis_net
    labels:
      - "traefik.enable=true"
      # Nova regra: Roteia para o backend se o Host for louis.tpfbrain.com E o caminho começar com /api
      - "traefik.http.routers.louis-backend.rule=Host(`louis.tpfbrain.com`) && PathPrefix(`/api`)"
      # Adiciona prioridade para garantir que esta regra seja avaliada antes da regra do frontend
      - "traefik.http.routers.louis-backend.priority=2"
      - "traefik.http.routers.louis-backend.entrypoints=websecure"
      - "traefik.http.routers.louis-backend.tls.certresolver=myresolver"
      - "traefik.http.services.louis-backend.loadbalancer.server.port=8000"
      - "traefik.network=louis_net"
      # Middleware para remover o prefixo /api antes de enviar para o container
      - "traefik.http.middlewares.strip-api-prefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.louis-backend.middlewares=strip-api-prefix"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: louis-frontend-prod
    restart: always
    depends_on:
      - backend
    networks:
      - louis_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.louis-frontend.rule=Host(`louis.tpfbrain.com`)"
      - "traefik.http.routers.louis-frontend.entrypoints=websecure"
      - "traefik.http.routers.louis-frontend.tls.certresolver=myresolver"
      - "traefik.http.services.louis-frontend.loadbalancer.server.port=80"
      - "traefik.network=louis_net"

volumes:
  letsencrypt_data:

networks:
  louis_net:
    driver: bridge 